# Generated by Django 5.0.6 on 2024-07-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payAt',
            new_name='paidAt',
        ),
    ]
